name: Terraform Lint & Validate
on:
  pull_request: {}
permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read
jobs:
  commitmsg-conform:
    uses: tfstack/actions/.github/workflows/terraform-lint-validate.yml@main
